import Head from 'next/head'
import { useEffect, useState } from 'react'
import getUsersList from '../services/getUsersList'
import { Container, Text } from '../styles/index.styles'
import { Pagination } from './components/Pagination'
import { UserFirstRow } from './components/UserFirstRow'
import { UserRow } from './components/UserRow'

export default function Home() {
  const [page, setPage] = useState(1000)
  const [usersList, setUsersList] = useState([{id: 0, login: ''}])

  useEffect(()=>{
    const usersListService = async (page: number) => {
      const response = await getUsersList(page)
      setUsersList(response.usersList)
  }

  usersListService(page)
      .catch(console.error)
  },[page])

  return (
    <Container >
      <Head>
        <Text>Create Next App</Text>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        usersList?.length > 1 ?
        <Container>
          <UserFirstRow />
          {
            usersList.map(user => {
              return (
                <UserRow
                  key={user.id}
                  id={user.id}
                  login={user.login}
                />
              )
            })
          }
        </Container> :
        <Text>Carregando Página...</Text>
      }
      <Pagination />
    </Container>
  )
}
