import Head from 'next/head'
import { useEffect, useState } from 'react'
import getUsersList from '../services/getUsersList'
import { ContainerIndex, TextIndex } from '../styles/index.styles'
import { Pagination } from './components/Pagination'
import { UserFirstRow } from './components/UserRowHeader'
import { UserRow } from './components/UserRow'

export default function Home() {
  const [page, setPage] = useState(0)
  const [usersListData, setUsersListData] = useState({
    usersList: [{id: 0, login: ''}],
    pageSize: 0,
    page: 0
})

  useEffect(()=>{
    const usersListService = async (page: number) => {
      const response = await getUsersList(page)
      setUsersListData(response)
  }

  usersListService(page)
      .catch(console.error)
  },[page])

  const pageInfo = (value: number) => {
    setPage(value)
}

  return (
    <ContainerIndex >
      <Head>
        <TextIndex>Create Next App</TextIndex>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        usersListData?.usersList?.length > 1 ?
        <ContainerIndex>
          <UserFirstRow />
          {
            usersListData.usersList.map(user => {
              return (
                <UserRow
                  key={user.id}
                  id={user.id}
                  login={user.login}
                />
              )
            })
          }
        </ContainerIndex> :
        <TextIndex>Carregando Página...</TextIndex>
      }
      <Pagination 
        count={usersListData.page}
        pageSize={usersListData.pageSize}
        sendPage={pageInfo}
      />
    </ContainerIndex>
  )
}
